name: Master and PR

on:
  push:
    branches: master
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get golint
      run: make golint

    - name: Lint
      run: make lint

    - name: Build
      run: make build-cross

    - name: Test
      run: make test     
