name: Release

on:
  push:
    tags: 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
      
    - name: Build mipsle
      run: make build-mipsle

    - name: Test
      run: make test

    # Dirty hack to upload multiple files - https://github.com/actions/upload-release-asset/issues/28#issuecomment-617208601
    - name: Create a draft release with binaries
      run: |
        set -x
        assets=()
        for asset in ./bin/*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create -d "${assets[@]}" -m "${tag_name}" "${tag_name}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
